# Generated by Django 3.2.9 on 2022-01-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_authtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='provinceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='customer.province'),
        ),
    ]
