# Generated by Django 3.2.9 on 2022-01-22 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Subcategories', to='shop.category')),
            ],
            options={
                'ordering': ['categoryId'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(max_length=800)),
                ('sizes', models.CharField(default='None', max_length=50, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The sizes must be comma seperated', regex='^([a-z0-9\\s]+,)*([a-z0-9\\s]+){1}$')])),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory')),
                ('tags', models.ManyToManyField(to='shop.Tags')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('imageColor', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
