# Generated by Django 3.2.9 on 2022-01-27 11:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_images_imagecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The sizes must be comma seperated', regex='^([a-z0-9\\s]+,)*([a-z0-9\\s]+){1}$')]),
        ),
    ]
