# Generated by Django 3.2.9 on 2022-03-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220310_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=60)),
                ('percentage', models.FloatField(default=0)),
                ('imageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.images', verbose_name='Image')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product')),
            ],
        ),
    ]
