# Generated by Django 3.2.9 on 2022-06-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
