# Generated by Django 3.2.9 on 2021-12-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211215_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='shop.product'),
        ),
    ]
