# Generated by Django 3.2.9 on 2021-11-27 19:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='None', max_length=50, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='The sizes must be comma seperated', regex='^([a-z0-9\\s]+,)*([a-z0-9\\s]+){1}$')]),
        ),
    ]
