# Generated by Django 3.2.9 on 2021-12-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imageColor',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
