# Generated by Django 3.2.9 on 2022-01-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_images_imagecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Subcategories', to='shop.category'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
