# Generated by Django 3.2.9 on 2021-11-24 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPurchase', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiryDate', models.DateField()),
                ('totalQuantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cuopenCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=3, max_digits=8)),
                ('shippingAddress', models.TextField()),
                ('receiverName', models.CharField(max_length=50)),
                ('receiverContact', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Contact number should consist of 11 digits')])),
                ('orderStatus', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^pending$|^received$', 'Order Status can only be pending,received')])),
                ('complaintStatus', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^null$|^solved$|^pending$', 'Order Status can only be null,pending,solved')])),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.city')),
                ('cuopenId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cuopen')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalQuantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=3, max_digits=8)),
                ('colourSelected', models.CharField(max_length=50)),
                ('sizeSelected', models.CharField(max_length=50)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(default=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
