# Generated by Django 3.2.9 on 2022-01-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customerId',
        ),
    ]
