# Generated by Django 3.2.9 on 2021-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderedproduct_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('pending', 'PENDING'), ('received', 'RECEIVED'), ('paymentPending', 'PAYMENTPENDING')], default='paymentPending', max_length=50),
        ),
    ]
