# Generated by Django 3.2.9 on 2021-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cuopen_cuopencode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complaintStatus',
            field=models.CharField(choices=[('NO', 'No Complain Yet'), ('pending', 'PENDING'), ('solved', 'SOLVED')], default='NO', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('pending', 'PENDING'), ('received', 'RECEIVED')], default='pending', max_length=50),
        ),
    ]
