# Generated by Django 3.2.9 on 2021-12-18 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuopen',
            name='discountPercentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
