# Generated by Django 3.2.9 on 2021-11-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211126_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='complaintStatus',
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintStatus', models.CharField(choices=[('pending', 'PENDING'), ('solved', 'SOLVED')], default='pending', max_length=50)),
                ('orderId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='complainId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.complaints'),
        ),
    ]
