# Generated by Django 3.2.9 on 2021-11-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211128_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='complainId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.complaints'),
        ),
    ]
