# Generated by Django 3.2.9 on 2022-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_strip_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('shipping', 'SHIPPING'), ('received', 'RECEIVED'), ('Payment pending', 'PAYMENTPENDING'), ('canceled', 'CANCELED')], default='PAYMENTPENDING', max_length=50),
        ),
    ]
