# Generated by Django 3.2.9 on 2021-12-18 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cuopen_discountpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuopen',
            name='totalQuantity',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
