# Generated by Django 3.2.9 on 2021-12-18 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cuopen_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuopen',
            name='totalQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
