# Generated by Django 3.2.9 on 2021-12-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211218_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order'),
        ),
    ]
