# Generated by Django 3.2.9 on 2022-03-10 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220310_1245'),
        ('customer', '0002_auto_20220310_1245'),
        ('orders', '0006_order_stripe_client_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='cuopen',
            options={'verbose_name_plural': 'Cuopens'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'get_latest_by': ['date', 'id'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaintStatus',
            field=models.CharField(choices=[('pending', 'PENDING'), ('solved', 'SOLVED')], default='pending', max_length=50, verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='orderId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='cuopen',
            name='cuopenCode',
            field=models.IntegerField(unique=True, verbose_name='Cuopen'),
        ),
        migrations.AlterField(
            model_name='cuopen',
            name='discountPercentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='cuopen',
            name='expiryDate',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='cuopen',
            name='minPurchase',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Purcase'),
        ),
        migrations.AlterField(
            model_name='cuopen',
            name='totalQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Quantity'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='orderedProductId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.orderedproduct', verbose_name='Ordered Product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='complainId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.complaints', verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cuopenId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cuopen', verbose_name='Cuopen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('shipping', 'SHIPPING'), ('received', 'RECEIVED'), ('Payment pending', 'PAYMENTPENDING'), ('canceled', 'CANCELED')], default='PAYMENTPENDING', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiverContact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Contact number should consist of 11 digits')], verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiverName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingAddress',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='strip_client_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Strip id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Strip secret'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='colourSelected',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Colour Selected'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedProducts', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderedProducts', to='shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='sizeSelected',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size Selected'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalPrice',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalQuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Quantity'),
        ),
    ]
