# Generated by Django 3.2.9 on 2021-12-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_complaints_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='complainId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.complaints'),
        ),
    ]
