# Generated by Django 3.2.9 on 2022-03-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220310_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_client_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Strip id')),
                ('stripe_client_secret', models.CharField(blank=True, max_length=500, null=True, verbose_name='Strip secret')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='strip_client_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_client_secret',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH')], default='CASH', max_length=10, verbose_name='Payment Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('shipping', 'SHIPPING'), ('received', 'RECEIVED'), ('Payment_Failed', 'PAYMENT_FAILED'), ('canceled', 'CANCELED')], max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stripe', verbose_name='Stripe'),
        ),
    ]
