# Generated by Django 3.2.9 on 2021-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211128_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'get_latest_by': ['date', 'id']},
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
