# Generated by Django 3.2.9 on 2022-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220310_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('shipping', 'SHIPPING'), ('received', 'RECEIVED'), ('Payment_pending', 'PAYMENTPENDING'), ('canceled', 'CANCELED')], max_length=20, verbose_name='Status'),
        ),
    ]
