# Generated by Django 3.2.9 on 2022-01-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220121_1858'),
        ('orders', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='orderedProductId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.orderedproduct'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderedProducts', to='shop.product'),
        ),
    ]
